spring:
  application:
    name: mcpClient
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.1-flash-lite
    mcp:
      client:
        enabled: true
        type: sync
        name: inventory-client
        version: 1.0.0
        toolcallback:
          enabled: true
        streamable-http:
          connections:
           ims-mcp-server:
              url: ${MCP_SERVER_URL:http://localhost:8082/mcp}

server:
  port: ${PORT:8081}

APP:
  CORS:
    ALLOWED:
      ORIGIN: ${FRONTEND_ORIGIN:http://localhost:5173}

logging:
  level:
    root: INFO
    org.springframework.ai.chat.client.advisor: DEBUG